README.md

WIP readme additions

---

README.md

- Update title
- Remove blockquote formatting from description to improve accessibility
- Capitalize "app" in "GitHub App" for consistency
- Add missing periods in unordered list
- Use new highlight syntax for note

docs(README): update title, description, formatting, and more

---

action.yml

https://github.com/marketplace/actions/github-app-token is taken, hence the rename

fix(action-config): prepare for release to marketplace

---

.github/workflows/release.yml

this should resolve the failing release workflow, it tries to push back with GITHUB_TOKEN and that one cannot bypass our branch protection rule
closes #25

ci(release): use installation access token to checkout and push back changes

---

.github/dependabot.yml
package.json

- Group production and development dependency updates
- Configure dependency update commit prefixes to release on production dependency updates
Dependabot commit messages before:
- `build(deps): bump semver from 7.5.1 to 7.5.4`
- `build(deps-dev): bump dotenv from 16.0.3 to 16.3.1`
Dependabot commit messages after:
- `fix(deps): bump semver from 7.5.1 to 7.5.4`
- `build(deps-dev): bump dotenv from 16.0.3 to 16.3.1` (no change to dev dependencies)

build(dependabot): Group dependency updates by type and configure commit prefixes

---

lib/main.js

The runner will automatically mask GitHub token formats it recognizes, but sometimes a new pattern rolls out before the runner is updated to recognize it.
closes #13

fix: mask the installation token in logs

---

README.md

With #13, this action is explicitly masking the token so I don't think we need to mention that we're relying on a specific format of GitHub tokens being masked by the runner.

docs(README): clarify token masking

---

lib/post.js

Check before trying to revoke the token, in case the token generation failed. Otherwise the post step will throw an error.

fix: check for token before revoking

---

.github/workflows/release.yml

fix(release): build `dist/` before release

---

lib/main.js
lib/post.js
main.js
post.js

This adds support for this action to be used in GitHub Enterprise Server.
It sends request to the base url extracted from [GITHUB_API_URL](https://docs.github.com/en/enterprise-server@3.10/actions/learn-github-actions/variables#default-environment-variables).

feat: add GitHub Enterprise Server (GHES) support

---

README.md

This is a quick follow-up to #59. I was mid-review when it merged and noticed one instance of `skip_token_revoke` in the README that didn't get changed to `skip-token-revoke`. The PR merged just before I pushed a commit to fix it.

docs: update `skip-token-revoke` input name

---

.github/workflows/release.yml

follow up to https://github.com/actions/create-github-app-token/pull/59#issuecomment-1751353971

ci(release): use local version

---

README.md

Using those fields that have an underscore (instead of a hyphen) cause the following warnings if used:
```
Warning: Input 'app_id' has been deprecated with message: 'app_id' is deprecated and will be removed in a future version. Use 'app-id' instead.
Warning: Input 'private_key' has been deprecated with message: 'private_key' is deprecated and will be removed in a future version. Use 'private-key' instead.
```
So this PR just drops the last use of `app_id` and `private_key` from the README in favor of `app-id` and `private-key`.

docs(README): fix use of deprecated arguments

---

dist/main.cjs
lib/main.js
package-lock.json
package.json
tests/main-repo-skew.js

GitHub's macOS runners for the past while have had some bad clock drift which sometimes prevents this action from working with the error:
```console
'Issued at' claim ('iat') must be an Integer representing the time that the assertion was issued
```
`@octokit/auth-app` already has logic to handle this so we can defer to that code.

fix: handle clock skew

---

README.md

This pull request includes a significant change to the `README.md` file. The change adds a new job to the GitHub Actions workflow, which is designed to create an example of how to use `create-github-app-token` action on GitHub Enterprise Server.
Resolves https://github.com/actions/create-github-app-token/issues/98

docs(README): add GHES workflow example

---

README.md
action.yml

Clarify the purpose of the `owner` input.
Resolves #116.

fix: clarify `owner` input description

---

README.md

docs(README): Create a git committer string for an app installation

---

README.md

I noticed the referenced ID in the committer string example doesn't seem to be correct.
Unrelated to this fix, I was wondering if there is interest in tweaking the example to be used with `git config`? I feel as if that is more generally useful than just echoing the string. For example
```
- name: setup git
run: |
git config user.name ${{steps.app-token.outputs.app-slug}}[bot]
git config user.email ${{ steps.app-token.outputs.installation-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>
```
It is the same content as the current example but ready to go for a common use case IMO.

docs(README): fix committer string example and add git config example

---

README.md

1. Fix the `git committer string` and `Configure git CLI` examples.
2. Formatting examples
3. Modify the get `<BOT USER ID>` comment and add a note that [octokit/request-action](https://github.com/octokit/request-action) can be used.

docs(README): fix the `git committer string` and `Configure git CLI` examples

---

README.md

Addressing this comment https://github.com/actions/create-github-app-token/issues/42#issuecomment-2214599409

docs(readme): document how a Base64 private key could be decoded

---

.github/dependabot.yml

This pull request updates the Dependabot configuration to only group minor and patch updates.

ci(dependabot): only group minor and patch updates

---

README.md

This PR fixes a syntax error in the "Create a git committer string for an app installation" example in the README file.  
The example contained an incorrect space in the variable syntax:  
```yaml  
${ {steps.committer.outputs.string }}  
```  
This caused the example to fail, as GitHub Actions does not allow spaces in variable interpolation.  
The syntax was corrected to:  
```yaml  
${{ steps.committer.outputs.string }}  
```  
This fix ensures that users can copy and use the example without encountering any errors.

docs(README): remove extra space in variable syntax in example

---

.github/CODEOWNERS

Since we have the `@actions/create-github-app-token-maintainers`, we don't need explicit references to individuals on that team.

Remove individuals form CODEOWNERS

---

package.json

This pull request updates the release configuration to include package-lock.json. This should ensure the action version is update in package-lock.json when the release workflow runs.

build: update package-lock.json on release

---

.github/workflows/update-inputs.yml

Resolves #220.
Updates action.yml inputs after an update to the octokit/openapi dependency.

ci(update-inputs): create initial version

---

.github/workflows/update-permission-inputs.yml

Adds `contents: write` permissions to the update-permission-inputs.yml workflow file.

ci(update-permission-inputs): add permissions

---

README.md

This PR aims to address issue https://github.com/actions/create-github-app-token/issues/232. Only minor changes, the README.md is already using the correct variables, only correcting the version was required.

fix(README): use `v2` in examples

---

.github/workflows/release.yml
package.json

Updated release workflow and semantic-release config to include the beta branch and pattern-matched branches for release automation. The beta branch is now marked as a prerelease.

Add beta branch support for releases
